name: Push a Sentiment Review Docker Image
on:
  push:
    branches: [ "main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements/requirements.txt
    - name: Train and save pipeline
      run: python sentimental_model/train_model.py
    - name: Upload trained model
      uses: actions/upload-artifact@v2
      with:
        name: sentiment-trained-model
        path: entimental_modeltrained_models/*.keras
        retention-days: 1
    - name: Upload tokenizer
      uses: actions/upload-artifact@v2
      with:
        name: sentiment-tokenizer
        path: sentimental_model/trained_models/*.json
        retention-days: 1

  test:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Copy trained model
      uses: actions/download-artifact@v2
      with:
        name: sentiment-trained-model
    - run: mv *.keras sentimental_model/trained_models/
    - name: Copy toeknizer
      uses: actions/download-artifact@v2
      with:
        name: sentiment-tokenizer
    - run: mv *.json sentimental_model/trained_models/
    - name: Install dependencies
      run: pip install -r requirements/test_requirements.txt
    - name: Test with pytest
      run: pytest

  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Copy trained model
      uses: actions/download-artifact@v2
      with:
        name: sentiment-trained-model
    - run: mv *.keras sentimental_model/trained_models/
    - name: Copy toeknizer
      uses: actions/download-artifact@v2
      with:
        name: sentiment-tokenizer
    - run: mv *.json sentimental_model/trained_models/
    - name: Install dependencies
      run: pip install --upgrade build
    - name: Build package
      run: python -m build
    - uses: actions/upload-artifact@v2
      with:
        name: my-build-package
        path: dist/*.whl

  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: my-build-package
    - run: mv *.whl sentimental_model/

    - name: Login to Docker hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the Docker image for Fastapi app
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker build . -f Dockerfile -t $DOCKER_USER/sentiment-fastapi-2:latest

    - name: Push the Docker Image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
      run: docker push $DOCKER_USER/sentiment-fastapi-2

    - name: Logout to Docker hub
      run: docker logout
